app:
  build: ./apps/api
  volumes:
    - ./apps/api:/src/api
  ports:
   - "3000:3000"
  environment:
    - HOME_DIR=/opt/application
    - NODE_ENV=development
    - NODE_CONFIG_DISABLE_FILE_WATCH=Y
    - NODE_LOGGER_LEVEL=info
    - NODE_LOGGER_GRANULARLEVELS=1
    - NODE_LOGGER_PLUGIN=util
    - NODE_CONFIG_DIR=/opt/application/config
    - NODE_HOT_RELOAD=1
    - NODE_LOG_DIR=/opt/application/logs
  command: [npm, run, docker-dev-start]
scrapper:
  build: ./apps/scrapper
  ports:
    - "8888:8888"
  links:
    - mongodb
  volumes:
    - ./apps/scrapper:/src/scrapper
    - ./apps/shared:/src/shared
  command: [npm, run, start]
mongoexpress:
  image: mongo-express:0.34
  links:
    - mongodb
  environment:
    ME_CONFIG_MONGODB_SERVER: mongodb
    ME_CONFIG_MONGODB_PORT: 27017
  ports:
    - "8081:8081"
mongodb:
  image: mongo:3
  ports:
    - "27017:27017"
